# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Tool shop demo tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  run-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          BASE_URL: ${{ env.BASE_URL }}
          ADMIN_EMAIL: ${{ env.ADMIN_EMAIL }}
          CUSTOMER_1_EMAIL: ${{ env.CUSTOMER_1_EMAIL }}
          CUSTOMER_2_EMAIL: ${{ env.CUSTOMER_2_EMAIL }}
          USER_PASSWORD: ${{ env.USER_PASSWORD }}
        run: npm run test
      - name: Archive tests results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: |
            ./playwright-report/**/*.*
            ./test-results/**/*.*
